---
title: An Epidemic Within the Pandemic: Changes in Opioid Overdose Death Characteristics During the COVID-19 Pandemic
author: Noah Willite, Akash Shanmugam (Emory University)
output: github_document
date: `r format(Sys.Date(), "%d-%m-%Y")`
editor_options:
  chunk_output_type: console
---

<!-- Short Description  -->


*Updated on `r Sys.time()`*

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}

library(rmarkdown)

knitr::opts_chunk$set(
  collapse = TRUE,
  out.width = "100%"
)
```


## Table of contents
* [General info](#general-info)
  * [Analyses](#Analyses)
    * [To do list](#to-do-list)
      * [Contact](#contact)

## General info
Our analyses are centered on characterizing the differences in opioid overdose rates among demographic groups before the pandemic and during the pandemic (2019 -2020). We hope that by identifying these trends, our work can inform policy initiatives to help those suffering from and affected by opioid use disorder. 


## Analysis
Analyses was conducted by Noah Willhite and Akash Shanmugam, students at Emory University, in Rstudio. Data is from the Multiple Cause of Death Dataset, years 2019/2020

We are interested in exploring how opioid overdose deaths compared between 2019 and 2020 among several demographic groups. We examined age groups, racial groups, groups based on education level, as well as which drugs were responsible for overdose deaths in 2019 and 2020.

Methods:
We categorized opioid overdose deaths as deaths where opioid overdose was listed as the primary cause of death. We then excluded deaths from January and February from analysis because COVID did not reach the United States until March 2020.
-2-sample z-test of proportions was used to analyze the proportion of total deaths before and after the pandemic
-Chi-square test was used to analyze changes in composition of race, type of opioid use, and education status.
-Linear Regression Analysis was used to analyze opioid overdose deaths before and after the pandemic. 

Next Steps:
We are interested in examining deaths where opioids were a contributing cause of death, not a primary cause of death. We found that synthetic opioids accounted for the hgihest proportion of overdose deaths, which makes sense because they are much more potent and are often consumed accidentally via lacing. We wonder if the opioids involved in "contributing cause of death" deaths would be different. We might expect to see a higher representation from methadone and heroin in such a study. 

Getting Started:
We recommend using the data importation protocols in the markdown file. This will make recoding and subsetting of the dataframe much easier. Besides this, there is nothing especially tricky about this program.

## In progress

*  Something not finished yet

## To-do list

* Do the next analysis

## Status
Project is: _in progress_

## Contact
Created by [Noah Willhite](https://mybinder.org/v2/gh/Noah-Willhite/QTM-302W-Project/main?urlpath=rstudio)
